# Generated by Django 3.0.8 on 2020-07-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="prober",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="only 1 user per prober"
            ),
        ),
    ]
