# Generated by Django 3.0.8 on 2020-07-28 02:22

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrefixInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("asn", models.PositiveIntegerField()),
                ("prefix", netfields.fields.CidrAddressField(max_length=43)),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=64)),
                ("country_code", models.CharField(max_length=3)),
                ("rir", models.CharField(max_length=16)),
            ],
        ),
    ]
