# Generated by Django 3.0.8 on 2020-07-20 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="probehop",
            name="result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hops",
                to="probes.ProbeResult",
            ),
        ),
    ]
