# Generated by Django 3.0.8 on 2020-07-25 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0002_auto_20200725_2235"),
    ]

    operations = [
        migrations.AddField(
            model_name="proberesult",
            name="probe",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="probes.Prober"
            ),
        ),
    ]
