# Generated by Django 3.0.8 on 2020-07-28 02:26

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0002_prefixinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prefixinfo",
            name="prefix",
            field=netfields.fields.CidrAddressField(max_length=43, unique=True),
        ),
    ]
