# Generated by Django 3.0.8 on 2020-07-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0003_auto_20200728_0226"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefixinfo",
            name="type",
            field=models.PositiveSmallIntegerField(choices=[(1, "RIR"), (2, "PRIVATE")], default=1),
            preserve_default=False,
        ),
    ]
