# Generated by Django 3.0.8 on 2020-07-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0003_proberesult_probe"),
    ]

    operations = [
        migrations.AddField(
            model_name="probetarget",
            name="probe_interval",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
