# Generated by Django 3.0.8 on 2020-07-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0003_prober"),
    ]

    operations = [
        migrations.AddField(
            model_name="prober",
            name="name",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
