# Generated by Django 3.0.8 on 2020-07-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0004_prefixinfo_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="prefixinfo", name="updated_at", field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="prefixinfo",
            name="asn",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prefixinfo",
            name="rir",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
