# Generated by Django 3.0.8 on 2020-07-26 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0004_probetarget_probe_interval"),
    ]

    operations = [
        migrations.RenameField(
            model_name="probetarget", old_name="probe_interval", new_name="probe_count",
        ),
    ]
