# Generated by Django 3.0.8 on 2020-07-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0005_auto_20200726_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probetarget',
            name='destination',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
