# Generated by Django 3.0.8 on 2020-07-28 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0005_auto_20200728_0245"),
    ]

    operations = [
        migrations.AddField(
            model_name="probehop",
            name="prefix",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="probes.PrefixInfo"
            ),
        ),
    ]
