# Generated by Django 3.0.8 on 2020-07-26 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0006_auto_20200726_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proberesult',
            name='probe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='probes.Prober'),
        ),
    ]
